# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               
tagline:             'familia'
description:         'casa de las colmenas'
url:                 http://lamalta.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              palma
  url:               https://twitter.com/?
  email:             palma@-.-

# Custom vars
version:             1.0.0
