#permalink:           pretty

# Setup
title:               familia
tagline:             more than just a hippie place
description:         casa de las colmenas
paginate:            5

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://lamalta.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#baseurl: 

# About/contact
author:
  name:              palma
  url:               https://twitter.com/?
  email:             palma@-.-

# Custom vars
version:             1.0.0

github:
    repo: https://github.com/lamalta/lamalta.github.io
